#!/bin/bash
# 4 Nodes pls
#SBATCH -N 4

# 16 tasks, da x task = 4 node * 4 task/node 
# Scheduling sollte für den Ausgleich sorgen
#SBATCH -n 16

# Out in timescript.out (obvious)
#SBATCH -o timescript.out

srun timescript
echo fertig > job_script.out
