#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
  echo '  Usage: prepare <dir-which-contains-code>'
  echo ''
  echo '  Will prepare the content to be deployed as a tar-ball with the given formalia.'
fi

id=WernerStruck
dir=$1
mkdir $id
cp -r $1/* $id/
tar -cvzf $id.tar.gz --exclude="*.out" $id
rm -rf $id
